import type { VisaRule } from '../visa-rule.js';

/**
 * visa_rules 시드 — VISA_RULES.md 3~5장이 정본이다.
 *
 * ⚠️ 이 데이터셋의 값은 대부분 2차 출처(민간 가이드) 기반이며
 *    「외국인유학생 사증발급 및 체류관리 지침」 원문과 대조되지 않았다.
 *    따라서 confidence 는 'low' 가 기본이고, low 규칙은 판정 시 UNKNOWN 을 유발한다 (CLAUDE.md L4).
 *
 * ⚠️ sourceUrl 이 null 인 행은 출처 URL 미확보 상태다.
 *    원문을 확보해 URL 을 채우고 rule_reviews 에 검수자를 기록해야
 *    confidence 를 'medium' 이상으로 올릴 수 있다 (VISA_RULES.md 8장).
 *
 * ⚠️ 규칙을 고칠 때는 이 배열의 행을 직접 수정하지 않는다.
 *    기존 행에 effectiveTo 를 넣고 새 행을 추가한다 (L2 — 과거 판정 재현성).
 */

const STUDENT_GUIDELINE = '외국인유학생 사증발급 및 체류관리 지침';
const STUDENT_EFFECTIVE_FROM = '2026-07-09';

export const VISA_RULES_SEED: VisaRule[] = [
  // ───────────────────────────────────────────────────────────────
  //  D-2 · 주당 시간 상한
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd2-hours-assoc-bachelor12-below-topik3',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: { degree_level: ['ASSOCIATE', 'BACHELOR_1_2'], korean_below: 'TOPIK3' },
    value: { hours: 10, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: '시간제취업 허용시간',
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: '2차 출처. 원문 미대조',
  },
  {
    id: 'd2-hours-assoc-bachelor12-topik3',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: { degree_level: ['ASSOCIATE', 'BACHELOR_1_2'], korean_min: 'TOPIK3' },
    value: { hours: 25, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: '시간제취업 허용시간',
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: '자료에 따라 25/30시간 상충',
  },
  {
    id: 'd2-hours-bachelor34-grad-below-topik4',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: {
      degree_level: ['BACHELOR_3_4', 'MASTER', 'DOCTORATE'],
      korean_below: 'TOPIK4',
    },
    value: { hours: 10, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: '시간제취업 허용시간',
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: null,
  },
  {
    id: 'd2-hours-bachelor34-grad-topik4',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: {
      degree_level: ['BACHELOR_3_4', 'MASTER', 'DOCTORATE'],
      korean_min: 'TOPIK4',
    },
    value: { hours: 30, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: '시간제취업 허용시간',
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: null,
  },

  // ───────────────────────────────────────────────────────────────
  //  D-2 · 금지 업종
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd2-industry-deny-manufacturing-below-topik4',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'INDUSTRY_DENY',
    appliesWhen: { korean_below: 'TOPIK4' },
    value: { ksic_prefixes: ['C', 'F'], labels: ['제조업', '건설업'] },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'INDUSTRY_DENIED_MANUFACTURING',
    note: 'TOPIK 4급 이상은 예외 심사 가능하나 재량 범위 불명 → 별도 재량 규칙으로 분리',
  },
  {
    /**
     * VISA_RULES.md 3.2 의 note("4급 이상에도 별도 WARN 규칙 필요")를 데이터로 구현한 행.
     * violationStatus='UNKNOWN' 이므로 매칭되면 INDETERMINATE 가 되고, 전체 판정은 UNKNOWN 이 된다.
     * "예외 심사 가능"은 "가능"이 아니다 (golden: D2-INDUSTRY-002).
     * ksic_prefixes 에 'F'(건설업)를 넣지 않는다 — 건설업에는 한국어 예외가 없다.
     */
    id: 'd2-industry-manufacturing-exception-discretionary',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'INDUSTRY_DENY',
    appliesWhen: { korean_min: 'TOPIK4' },
    value: { ksic_prefixes: ['C'], labels: ['제조업'] },
    violationStatus: 'UNKNOWN',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'INDUSTRY_EXCEPTION_DISCRETIONARY',
    note: '심사 재량 범위 불명. 원문 확인 전까지 ELIGIBLE 로 올리지 않는다',
  },
  {
    id: 'd2-industry-deny-construction',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'INDUSTRY_DENY',
    appliesWhen: {},
    value: { ksic_prefixes: ['F'], labels: ['건설업'] },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'INDUSTRY_DENIED_CONSTRUCTION',
    note: '한국어 급수와 무관하게 금지',
  },
  {
    id: 'd2-industry-deny-seafarer',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'INDUSTRY_DENY',
    appliesWhen: {},
    value: { ksic_prefixes: ['H501', 'H502'], labels: ['선원취업'] },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'INDUSTRY_DENIED_SEAFARER',
    note: null,
  },

  // ───────────────────────────────────────────────────────────────
  //  D-2 · 금지 고용형태 — 물류·배달 공고 대부분이 여기 걸린다
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd2-employment-form-deny',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'EMPLOYMENT_FORM_DENY',
    appliesWhen: {},
    value: {
      forms: ['DISPATCH', 'SUBCONTRACT', 'PLATFORM'],
      labels: ['파견', '도급', '특수형태근로(배달·택배·대리·보험설계·학습지·방문판매)'],
    },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'EMPLOYMENT_FORM_DENIED',
    note: '여러 2차 출처가 일치 → medium',
  },

  // ───────────────────────────────────────────────────────────────
  //  D-2 · 통학 거리 — 🔴 자료 상충. 원문 확인 전까지 low 고정
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd2-commute-capital-area-semester',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'COMMUTE_MAX_MINUTES',
    appliesWhen: { region: 'CAPITAL_AREA', term: 'SEMESTER' },
    value: { minutes: 60, alternative_claim: 90 },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'COMMUTE_EXCEEDED',
    note: '자료 A: 학기 중 60분 / 자료 B: 수도권 90분·지방 60분. 원문 확인 필수',
  },

  // ───────────────────────────────────────────────────────────────
  //  D-2 · 사전 허가 — 미보유는 불가가 아니라 조건부다
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd2-permit-required',
    visa: 'D2',
    visaSubtype: null,
    ruleType: 'PERMIT_REQUIRED',
    appliesWhen: {},
    value: {
      permit: 'PART_TIME_WORK_PERMIT',
      steps: [
        '표준근로계약서 작성',
        '학교 유학생 담당자 확인서 발급',
        '하이코리아 또는 출입국관서 신청',
        '허가 완료 후 근무 시작',
      ],
      documents: [
        '여권',
        '외국인등록증',
        '통합신청서',
        '시간제취업 확인서',
        '재학증명서',
        '성적/출석증명서',
        '한국어능력 증빙',
        '표준근로계약서',
        '사업자등록증 사본',
      ],
      fee_krw: 20000,
      warning: '허가 완료 전 근무 불가',
    },
    violationStatus: 'CONDITIONAL',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'PERMIT_REQUIRED_PART_TIME',
    note: '신청 중 근무는 불법. UI에서 강조할 것',
  },

  // ───────────────────────────────────────────────────────────────
  //  D-4
  // ───────────────────────────────────────────────────────────────
  {
    id: 'd4-hours-below-topik2',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: { korean_below: 'TOPIK2' },
    value: { hours: 10, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: null,
  },
  {
    id: 'd4-hours-topik2',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'WEEKLY_HOUR_CAP',
    appliesWhen: { korean_min: 'TOPIK2' },
    value: { hours: 20, term: 'SEMESTER' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'WEEKLY_HOUR_EXCEEDED',
    note: 'TOPIK 2급/KIIP 2단계 기준',
  },
  {
    id: 'd4-employment-form-deny',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'EMPLOYMENT_FORM_DENY',
    appliesWhen: {},
    value: { forms: ['DISPATCH', 'SUBCONTRACT', 'PLATFORM'] },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'EMPLOYMENT_FORM_DENIED',
    note: null,
  },
  {
    id: 'd4-industry-deny',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'INDUSTRY_DENY',
    appliesWhen: {},
    value: { ksic_prefixes: ['C', 'F'], labels: ['제조업', '건설업'] },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'INDUSTRY_DENIED_MANUFACTURING',
    note: 'D-4는 TOPIK 4급 예외가 적용되는지 불명확 → 원문 확인 필요',
  },
  {
    id: 'd4-commute-capital-area-semester',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'COMMUTE_MAX_MINUTES',
    appliesWhen: { region: 'CAPITAL_AREA', term: 'SEMESTER' },
    value: { minutes: 60, alternative_claim: 90 },
    violationStatus: 'INELIGIBLE',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'low',
    reasonCode: 'COMMUTE_EXCEEDED',
    note: 'D-2와 동일한 상충. 원문 확인 필수',
  },
  {
    id: 'd4-permit-required',
    visa: 'D4',
    visaSubtype: null,
    ruleType: 'PERMIT_REQUIRED',
    appliesWhen: {},
    value: { permit: 'PART_TIME_WORK_PERMIT', warning: '허가 완료 전 근무 불가' },
    violationStatus: 'CONDITIONAL',
    sourceTitle: STUDENT_GUIDELINE,
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: STUDENT_EFFECTIVE_FROM,
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'PERMIT_REQUIRED_PART_TIME',
    note: null,
  },

  // ───────────────────────────────────────────────────────────────
  //  E-9 — MVP UI 미노출. 엔진·스키마 레벨만 지원한다 (CLAUDE.md 1장)
  //  이 판정을 화면에 쓸 때는 E9_NO_BROKERAGE_I18N_KEY 고지를 반드시 함께 출력한다 (L1)
  // ───────────────────────────────────────────────────────────────
  {
    id: 'e9-region-lock',
    visa: 'E9',
    visaSubtype: null,
    ruleType: 'REGION_LOCK',
    appliesWhen: {},
    value: { scope: 'SAME_REGION' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: '외국인력정책위원회 사업장 변경 제도 개선방안 (2023-07-05)',
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: '2023-07-05',
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'REGION_LOCKED',
    note: '권역 구분 코드 정의 필요',
  },
  {
    id: 'e9-industry-lock',
    visa: 'E9',
    visaSubtype: null,
    ruleType: 'INDUSTRY_LOCK',
    appliesWhen: {},
    value: { scope: 'SAME_INDUSTRY' },
    violationStatus: 'INELIGIBLE',
    sourceTitle: '외국인력정책위원회 사업장 변경 제도 개선방안 (2023-07-05)',
    sourceClause: null,
    sourceUrl: null,
    effectiveFrom: '2023-07-05',
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'INDUSTRY_LOCKED',
    note: null,
  },
  {
    id: 'e9-change-count-cap',
    visa: 'E9',
    visaSubtype: null,
    ruleType: 'CHANGE_COUNT_CAP',
    appliesWhen: {},
    value: {
      max_changes: 3,
      exceptions: ['휴업', '폐업', '임금체불', '근로조건 위반', '부당처우'],
    },
    violationStatus: 'INELIGIBLE',
    sourceTitle: '외국인근로자의 고용 등에 관한 법률 제25조',
    sourceClause: '제25조',
    sourceUrl: null,
    effectiveFrom: '2021-01-01',
    effectiveTo: null,
    confidence: 'medium',
    reasonCode: 'CHANGE_COUNT_EXCEEDED',
    note: null,
  },
];
